version: '3.8'

services:
  db:
    image: mysql:5.7
    container_name: mysql_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 0000
      MYSQL_DATABASE: tpachat2
    volumes:
      - db_data:/var/lib/mysql

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

  nexus:
    image: sonatype/nexus3
    container_name: nexus
    ports:
      - "8081:8081" # Adjust the port mapping as needed
    volumes:
      - nexus-data:/nexus-data # Persistent volume for Nexus data
    environment:
      - NEXUS_SECURITY_RANDOMPASSWORD=false # Disable random password generation
      - NEXUS_ADMIN_PASSWORD=admin123 # Set your desired admin password

  sonarqube:
    image: sonarqube
    container_name: sonarqube
    ports:
      - "9000:9000" # Adjust the port mapping as needed
    volumes:
      - sonarqube-data:/opt/sonarqube/data # Persistent volume for SonarQube data
      - sonarqube-extensions:/opt/sonarqube/extensions # Persistent volume for SonarQube extensions
      - sonarqube-logs:/opt/sonarqube/logs # Persistent volume for SonarQube logs
    environment:
      - SONAR_JDBC_URL=jdbc:mysql://mysql_db:3306/tpachat2
      - SONAR_JDBC_USERNAME=root
      - SONAR_JDBC_PASSWORD=0000

volumes:
  db_data:
  prometheus_data:
  nexus-data:
  sonarqube-data:
  sonarqube-extensions:
  sonarqube-logs:
