FROM openjdk:11-jdk-slim
WORKDIR /app
COPY target/4CARCTIC-G1-tpAchatProject1-0.0.jar 4CARCTIC-G1-tpAchatProject1-0.0.jar
EXPOSE 8089
ENTRYPOINT ["java", "-jar", "4CARCTIC-G1-tpAchatProject1-0.0.jar"]
